<!DOCTYPE html>
<html lang="en"><head>
<script src="01-rstats-presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="01-rstats-presentation_files/libs/quarto-html/tabby.min.js"></script>
<script src="01-rstats-presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="01-rstats-presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="01-rstats-presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="01-rstats-presentation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="01-rstats-presentation_files/libs/quarto-html/quarto-syntax-highlighting-de070a7b0ab54f8780927367ac907214.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.30">

  <title>Doing Statistics in R</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="01-rstats-presentation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="01-rstats-presentation_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="01-rstats-presentation_files/libs/revealjs/dist/theme/quarto-f563837468303362081e247dddd440d0.css">
  <link rel="stylesheet" href="styles.css">
  <link href="01-rstats-presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="01-rstats-presentation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="01-rstats-presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="01-rstats-presentation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Doing Statistics in R</h1>
  <p class="subtitle">StatLab Workshop 01: Introduction to R</p>

<div class="quarto-title-authors">
</div>

</section>
<section id="by-the-end-of-today" class="slide level2">
<h2>By the end of today</h2>
<p>You will have run a complete statistical analysis in R:</p>
<ul>
<li class="fragment">read real data and looked at it</li>
<li class="fragment">compared two groups and tested the difference</li>
<li class="fragment">visualize and assess patterns in your data</li>
<li class="fragment">fit a regression and read the output</li>
</ul>
<div class="fragment">
<p>It takes twenty-three functions. That is the whole list.</p>
</div>
</section>
<section id="what-todays-workshop-is-not" class="slide level2">
<h2>What today’s workshop is not</h2>
<ul>
<li class="fragment">a crash course in R programming (e.g., objects, functions, loops)</li>
<li class="fragment">a crash course in hypothesis testing</li>
</ul>
</section>
<section id="playing-the-ballgame-early" class="slide level2">
<h2>Playing the Ballgame Early</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="mets-stadium.jpeg" class="quarto-figure quarto-figure-center" style="width:100.0%"></p>
</figure>
</div>
</div><div class="column" style="width:40%;">
<ul>
<li class="fragment">Today’s workshop is about learning R by <em>doing</em> statistics.</li>
<li class="fragment">Our goal today is to get you comfortable playing a <em>junior</em> version of the whole ballgame:</li>
</ul>
</div></div>
<div class="fragment ballgame-flow">
<p><img data-src="../assets/ballgame-flow.svg" alt="question, data, describe, visualize, model, report"></p>
</div>
</section>
<section id="todays-question" class="slide level2">
<h2>Today’s question</h2>
<blockquote>
<p><strong>Did states that expanded Medicaid in 2014 have lower working-age mortality than states that did not?</strong></p>
</blockquote>
</section>
<section id="todays-ballgame" class="slide level2">
<h2>Today’s Ballgame</h2>
<p>Explore: What does mortality look like across states that expanded medicade and those that did not? &nbsp;&nbsp;→ <code>hist()</code>, <code>boxplot()</code>, group means</p>
<p>Test: Is the difference in these states bigger than chance would produce? &nbsp;&nbsp;→ <code>t.test(rate ~ expanded)</code></p>
<p>Check: does the answer to our second question depend on unreasonable assumptions? &nbsp;&nbsp;→ permutation test</p>
<p>Extend: how can we formally express and model these differences?. &nbsp;&nbsp;→ <code>lm(rate ~ expanded)</code></p>
</section>
<section id="how-today-works" class="slide level2">
<h2>How today works</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Module 1</strong></td>
<td>I do</td>
<td>I drive. You type every line with me.</td>
</tr>
<tr class="even">
<td><strong>Module 2</strong></td>
<td>We do</td>
<td>Pairs. Most of the code is given; you write the four that matter.</td>
</tr>
<tr class="odd">
<td><strong>Module 3</strong></td>
<td>You do</td>
<td>On your own. Eight steps, no code.</td>
</tr>
</tbody>
</table>
<p>The analysis is the <em>same shape</em> all three times. That is deliberate, because by the third pass, the shape is yours.</p>
</section>
<section id="two-rules" class="slide level2 scrollable">
<h2>Two rules</h2>
<ol type="1">
<li class="fragment"><strong>Type it, don’t read it.</strong> Watching me will not put it in your hands.</li>
<li class="fragment"><strong>Errors are the job, not a failure.</strong> I will make several on purpose. You will make more by accident. This never stops, for anyone.</li>
</ol>
<div class="fragment">
<p>Red sticky = stuck. Green = through. Put the red one up early.</p>
</div>
</section>
<section>
<section id="setup" class="title-slide slide level1 center">
<h1>Setup</h1>

</section>
<section id="getting-in" class="slide level2 scrollable">
<h2>Getting in</h2>
<p>We are using <strong>Positron</strong>, Posit’s data-science IDE, the one they are building next after RStudio.</p>
<ol type="1">
<li class="fragment"><strong>File → Open Folder</strong>, and choose the <code>01-RStats</code> folder</li>
<li class="fragment">Check the top-right corner says <strong>R</strong>. That is your interpreter</li>
<li class="fragment">Open <code>scripts/01-i-do.R</code> from the file list on the left</li>
<li class="fragment">Run a line with <strong>Cmd+Enter</strong> (Mac) / <strong>Ctrl+Enter</strong> (Windows)</li>
</ol>
<div class="fragment">
<p>Open the <strong>folder</strong>, not a file. Positron makes whatever folder you open the working directory, which is the whole reason we will never type a file path today.</p>
</div>
</section>
<section id="the-parts-you-need-today" class="slide level2">
<h2>The parts you need today</h2>
<div class="ide-map">
<div class="activity">
<p>Activity Bar</p>
</div>
<div class="explorer">
<p><span class="label">Explorer</span> Your files. <code>scripts/</code>, <code>data/</code>, and the rest of the folder you opened.</p>
</div>
<div class="key">
<p><span class="label">Editor</span> Where you <strong>write</strong>.</p>
<p><code>scripts/01-i-do.R</code> opens here.</p>
<p><strong>Cmd+Enter</strong> sends the current line down to the Console.</p>
</div>
<div class="key side">
<p><span class="label">Variables</span> What currently <strong>exists</strong>. Watch <code>states</code> appear here when you make it.</p>
<p><span class="label">Plots</span> Where <strong>pictures</strong> land.</p>
<div class="ide-note">
<p>Both live in the right sidebar. Click between them.</p>
</div>
</div>
<div class="key">
<p><span class="label">Console</span> Where it <strong>runs</strong>. Your code arrives here, and R answers underneath.</p>
</div>
</div>
</section>
<section id="two-things-positron-gives-you" class="slide level2">
<h2>Two things Positron gives you</h2>
<p><strong>The Data Explorer.</strong> Click a data frame in <strong>Variables</strong> and you get a real spreadsheet view: sort it, filter it, see the type and missingness of every column. It is the fastest way to answer “what am I actually looking at?”</p>
<p><strong>One IDE for R and Python.</strong> The interpreter picker in the top-right switches languages. Nothing today needs it, but it is why Positron exists.</p>
<div class="fragment">
<p>Everything else (the Command Palette, extensions, source control) you can ignore for three hours. Editor, Console, Variables, Plots. That is the whole interface today.</p>
</div>
</section></section>
<section>
<section id="module-1-i-do" class="title-slide slide level1 center">
<h1>Module 1: I do</h1>

</section>
<section id="two-things-to-name-first" class="slide level2">
<h2>Two things to name first</h2>
<p>Everything in R is an <strong>object</strong> or a <strong>function</strong>.</p>
<ul>
<li class="fragment">An <strong>object</strong> is something you made and gave a name to. It sits in the Variables pane until you overwrite it or close R.</li>
<li class="fragment">A <strong>function</strong> does something. You give it a name, a pair of parentheses, and whatever it needs to know inside them.</li>
</ul>
<div class="fragment">
<p>That is the whole vocabulary. Every line today is one or both.</p>
</div>
</section>
<section id="anatomy-of-a-function-call" class="slide level2">
<h2>Anatomy of a function call</h2>
<div class="anatomy big">
<p><span class="fragment highlight-current-red" data-fragment-index="1">read.csv</span><span class="fragment highlight-current-red" data-fragment-index="2">(</span><span class="fragment highlight-current-red" data-fragment-index="3">“data/medicaid.csv”</span><span class="fragment highlight-current-red" data-fragment-index="5">,&nbsp;</span><span class="fragment highlight-current-red" data-fragment-index="4">row.names&nbsp;=&nbsp;1</span><span class="fragment highlight-current-red" data-fragment-index="2">)</span></p>
</div>
<div class="fragment" data-fragment-index="1">
<p><strong><code>read.csv</code></strong> is the function name. It says what you want done.</p>
</div>
<div class="fragment" data-fragment-index="2">
<p><strong><code>( )</code></strong> holds everything the function needs to know.</p>
</div>
<div class="fragment" data-fragment-index="3">
<p><strong><code>"data/medicaid.csv"</code></strong> is the first argument: which file to read.</p>
</div>
<div class="fragment" data-fragment-index="4">
<p><strong><code>row.names = 1</code></strong> is a named argument. It changes how the function behaves: treat column 1 as row labels, not data. That is why we get 13 columns from a 14-column file.</p>
</div>
<div class="fragment" data-fragment-index="5">
<p><strong><code>,</code></strong> separates one argument from the next.</p>
</div>
<div class="fragment" data-fragment-index="6">
<p>Two questions get you through any function: <strong>what do I want R to do</strong>, and <strong>what does R need to know to do it?</strong></p>
</div>
</section>
<section id="step-1-read-the-data" class="slide level2">
<h2>Step 1: read the data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a>counties <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/medicaid.csv"</span>, <span class="at">row.names =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Nothing printed. That is what success looks like: <code>&lt;-</code> stores silently.</p>
<div class="fragment">
<p>Look at the <strong>Variables</strong> pane. <code>counties</code> is now in it.</p>
</div>
</section>
<section id="step-1-three-questions" class="slide level2">
<h2>Step 1: three questions</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="fu">dim</span>(counties)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 26066    13</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="fu">names</span>(counties)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "state"            "county"           "county_code"     
 [4] "year"             "population_20_64" "yaca"            
 [7] "perc_white"       "perc_hispanic"    "perc_female"     
[10] "crude_rate_20_64" "unemp_rate"       "poverty_rate"    
[13] "median_income"   </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a><span class="fu">head</span>(counties, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  state             county county_code year population_20_64 yaca perc_white
1    AL Autauga County, AL        1001 2009            31271   NA   80.42915
2    AL Autauga County, AL        1001 2010            31875   NA   80.44549
3    AL Autauga County, AL        1001 2011            32538   NA   79.56850
  perc_hispanic perc_female crude_rate_20_64 unemp_rate poverty_rate
1      2.078603    51.48220         412.5228   8.905110         11.2
2      2.240000    51.38196         423.5294   8.808109         11.9
3      2.311144    51.14635         482.5128   8.345908         14.9
  median_income
1        53.081
2        53.049
3        48.863</code></pre>
</div>
</div>
<p>Ask these of every new dataset: <strong>how big, what columns, what’s a row.</strong></p>
</section>
<section id="step-2-look-at-the-outcome" class="slide level2">
<h2>Step 2: look at the outcome</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a><span class="fu">hist</span>(counties<span class="sc">$</span>crude_rate_20_64)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="01-rstats-presentation_files/figure-revealjs/unnamed-chunk-7-1.png" class="quarto-figure quarto-figure-center r-stretch" width="864"><p>Never test a variable you have not looked at. Defaults are fine; we are not decorating anything yet.</p>
</section>
<section id="what-is-that" class="slide level2">
<h2>What is that <code>$</code>?</h2>
<div style="font-size: 1.3em; text-align: center; margin: 0.6em 0;">
<p><code>hist(counties</code><span class="pop"><code>$</code></span><code>crude_rate_20_64)</code></p>
</div>
<p>You have not seen that symbol before. <strong>Don’t look it up yet.</strong></p>
<div class="fragment">
<p>Use what is already on the screen:</p>
</div>
<ul>
<li class="fragment"><code>counties</code> is the table you just read in</li>
<li class="fragment"><code>crude_rate_20_64</code> was in the list <code>names()</code> printed</li>
<li class="fragment">so <code>$</code> has to join <strong>a table</strong> to <strong>one of its columns</strong></li>
</ul>
<div class="fragment">
<blockquote>
<p>“<code>counties</code> … the <code>crude_rate_20_64</code> one.”</p>
</blockquote>
</div>
</section>
<section id="use-the-context-clues" class="slide level2">
<h2>Use the context clues</h2>
<p>You just read a symbol you had never seen, correctly, without looking it up.</p>
<ul>
<li class="fragment">Unfamiliar R code is usually surrounded by things you do recognise: a table you made, a column you have seen, a function whose name says what it does.</li>
<li class="fragment">Read around the gap first. The shape of the line tells you what the missing piece has to be.</li>
<li class="fragment">Then check. Guessing and confirming is faster than looking up cold, and you remember it longer.</li>
</ul>
</section>
<section id="reading-from-the-inside-out" class="slide level2 scrollable">
<h2>Reading from the inside out</h2>
<p><code>hist(counties$crude_rate_20_64)</code> has two steps, and the inner one happens first.</p>
<ol type="1">
<li class="fragment"><code>counties$crude_rate_20_64</code> pulls the column out. On its own it is a vector: one number per county.</li>
<li class="fragment"><code>hist()</code> draws that vector.</li>
</ol>
<div class="fragment">
<blockquote>
<p>“Take the <code>crude_rate_20_64</code> column out of <code>counties</code>, and draw a histogram of it.”</p>
</blockquote>
</div>
</section>
<section id="step-3-expansion-is-a-state-policy" class="slide level2">
<h2>Step 3: expansion is a state policy</h2>
<p>Every county in Alabama has the same Medicaid policy as every other county in Alabama.</p>
<div class="fragment">
<p>So the thing that varies is the <strong>state</strong>, not the county. Thirty-nine states decided; 2,372 counties did not each decide separately.</p>
</div>
<div class="fragment">
<p>We need one row per state before we compare anything. That takes three moves: keep one year, label each state, then average to the state.</p>
</div>
</section>
<section id="step-3a-keep-one-year" class="slide level2">
<h2>Step 3a: keep one year</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a>d2014 <span class="ot">&lt;-</span> counties[counties<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">2014</span>, ]</span>
<span id="cb9-2"><a href=""></a><span class="fu">dim</span>(d2014)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2372   13</code></pre>
</div>
</div>
<div class="fragment">
<p>Square brackets take a slice: <code>df[rows, columns]</code>. We asked for rows where <code>year</code> is 2014, and left the column slot blank to mean “all of them”.</p>
</div>
<div class="fragment">
<p><code>==</code> asks <em>is this equal to</em>. It is a question, not an instruction — that is why it is doubled.</p>
</div>
</section>
<section id="reading-a-line-right-to-left" class="slide level2">
<h2>Reading a line, right to left</h2>
<div style="font-size: 1.05em; text-align: center; margin: 0.5em 0;">
<p><code>d2014 &lt;- counties[counties$year == 2014, ]</code></p>
</div>
<p>Longer lines are still one sentence. Start at the right:</p>
<ul>
<li class="fragment"><code>counties[counties$year == 2014, ]</code> says <em>from <code>counties</code>, keep the rows where <code>year</code> is 2014, and every column</em> …</li>
<li class="fragment"><code>&lt;-</code> says <em>… and store it</em> …</li>
<li class="fragment"><code>d2014</code> says <em>… as <code>d2014</code>.</em></li>
</ul>
<div class="fragment">
<blockquote>
<p>“<strong>From <code>counties</code>, keep the rows where <code>year</code> is 2014 and every column, and store that as <code>d2014</code>.</strong>”</p>
</blockquote>
</div>
<div class="fragment">
<p>Whatever is left of the arrow is the name you are giving to the result. If you can say a line out loud, you understand it. If you cannot, that is where to stop and ask.</p>
</div>
</section>
<section id="step-3b-label-each-state" class="slide level2">
<h2>Step 3b: label each state</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a>d2014<span class="sc">$</span>expanded <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="sc">!</span><span class="fu">is.na</span>(d2014<span class="sc">$</span>yaca) <span class="sc">&amp;</span> d2014<span class="sc">$</span>yaca <span class="sc">==</span> <span class="dv">2014</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb11-2"><a href=""></a><span class="fu">table</span>(d2014<span class="sc">$</span>expanded)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   0    1 
1337 1035 </code></pre>
</div>
</div>
<p><code>ifelse(test, value_if_true, value_if_false)</code> runs down the whole column.</p>
<div class="fragment">
<p>Note <code>$</code> doing a second job: on the <strong>left</strong> of <code>&lt;-</code> it creates a column rather than pulling one out.</p>
</div>
</section>
<section id="why-the-is.na-guard" class="slide level2">
<h2>Why the <code>!is.na()</code> guard</h2>
<p>States that never expanded have <code>yaca = NA</code>.</p>
<div class="fragment">
<p><code>NA == 2014</code> is not <code>FALSE</code>. It is <code>NA</code> — R is saying “I don’t know.”</p>
</div>
<div class="fragment">
<p>Without the guard, every one of those rows comes back <code>NA</code>, R gives no error, and every mean you compute afterwards is <code>NA</code>. <code>!</code> means “not” and <code>&amp;</code> means “and”, so the guard reads: <em>not missing, and equal to 2014.</em></p>
</div>
<div class="fragment">
<p>Silent wrong answers are worse than errors. This is the most common way R hands you one.</p>
</div>
</section>
<section id="ask-r-itself" class="slide level2 scrollable">
<h2>Ask R itself</h2>
<div class="sourceCode" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a>?mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The help page opens in the <strong>Help</strong> pane. The <strong>Usage</strong> line at the top lists every argument and its default:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a><span class="fu">mean</span>(x, <span class="at">trim =</span> <span class="dv">0</span>, <span class="at">na.rm =</span> <span class="cn">FALSE</span>, ...)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="fragment">
<p>Three questions for the room:</p>
<ol type="1">
<li>How many arguments does <code>mean()</code> take?</li>
<li>What does <code>na.rm</code> do? (scroll to <strong>Arguments</strong>)</li>
<li>What is it set to if you don’t say?</li>
</ol>
</div>
</section>
<section id="na.rm-false-is-the-default" class="slide level2">
<h2><code>na.rm = FALSE</code> is the default</h2>
<p>R will not skip missing values unless you tell it to.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a><span class="fu">mean</span>(counties<span class="sc">$</span>median_income)</span>
<span id="cb15-2"><a href=""></a><span class="co">#&gt; NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Fifteen county-year rows are missing an income. One <code>NA</code> is enough to make the whole answer <code>NA</code>.</p>
<div class="fragment">
<div class="sourceCode" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href=""></a><span class="fu">mean</span>(counties<span class="sc">$</span>median_income, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-2"><a href=""></a><span class="co">#&gt; 47.09</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="fragment">
<p>This is the most common “why is my result <code>NA</code>?” in R. When it happens, <code>?</code> the function and look at what its defaults were doing.</p>
</div>
</section>
<section id="step-3c-average-to-the-state" class="slide level2">
<h2>Step 3c: average to the state</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a>states_unwt <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(crude_rate_20_64 <span class="sc">~</span> state <span class="sc">+</span> expanded,</span>
<span id="cb17-2"><a href=""></a>                         <span class="at">data =</span> d2014, <span class="at">FUN =</span> mean)</span>
<span id="cb17-3"><a href=""></a><span class="fu">dim</span>(states_unwt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39  3</code></pre>
</div>
</div>
<p>Read it out loud: <em>average <code>crude_rate_20_64</code>, by state and expansion status.</em></p>
<div class="fragment">
<p><code>FUN = mean</code> passes the function itself, with no parentheses. <code>FUN = mean()</code> would try to run it right now, on nothing.</p>
</div>
</section>
<section id="the-formula-y-x" class="slide level2">
<h2>The formula: <code>y ~ x</code></h2>
<p>That squiggle is the most reusable thing you will learn today.</p>
<div style="font-size: 1.5em; text-align: center; margin: 0.5em 0;">
<p><code>goal( y ~ x , data = d )</code></p>
</div>
<p>Read <code>~</code> as <strong>“broken down by”</strong>.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><code>aggregate(rate ~ expanded, data = states, FUN = mean)</code></td>
<td>group means</td>
</tr>
<tr class="even">
<td><code>boxplot(rate ~ expanded, data = states)</code></td>
<td>a picture</td>
</tr>
<tr class="odd">
<td><code>t.test(rate ~ expanded, data = states)</code></td>
<td>a test</td>
</tr>
<tr class="even">
<td><code>lm(rate ~ expanded, data = states)</code></td>
<td>a model</td>
</tr>
</tbody>
</table>
<p>You have used it once. You will use it four more times before lunch.</p>
</section>
<section id="that-line-hid-a-decision" class="slide level2">
<h2>That line hid a decision</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href=""></a><span class="fu">range</span>(d2014<span class="sc">$</span>population_20_64)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]     224 6298815</code></pre>
</div>
</div>
<div class="fragment">
<p>224 people, and 6.3 million. Averaging county <strong>rates</strong> gave Loving County, Texas the same weight as Los Angeles.</p>
</div>
</section>
<section id="a-rate-is-deaths-over-people" class="slide level2">
<h2>A rate is deaths over people</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href=""></a>d2014<span class="sc">$</span>deaths <span class="ot">&lt;-</span> d2014<span class="sc">$</span>crude_rate_20_64 <span class="sc">*</span> d2014<span class="sc">$</span>population_20_64 <span class="sc">/</span> <span class="fl">1e5</span></span>
<span id="cb21-2"><a href=""></a></span>
<span id="cb21-3"><a href=""></a>state_deaths <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(deaths <span class="sc">~</span> state <span class="sc">+</span> expanded, <span class="at">data =</span> d2014, <span class="at">FUN =</span> sum)</span>
<span id="cb21-4"><a href=""></a>state_people <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(population_20_64 <span class="sc">~</span> state <span class="sc">+</span> expanded, <span class="at">data =</span> d2014, <span class="at">FUN =</span> sum)</span>
<span id="cb21-5"><a href=""></a></span>
<span id="cb21-6"><a href=""></a>states <span class="ot">&lt;-</span> state_deaths</span>
<span id="cb21-7"><a href=""></a>states<span class="sc">$</span>crude_rate_20_64 <span class="ot">&lt;-</span> state_deaths<span class="sc">$</span>deaths <span class="sc">/</span></span>
<span id="cb21-8"><a href=""></a>                           state_people<span class="sc">$</span>population_20_64 <span class="sc">*</span> <span class="fl">1e5</span></span>
<span id="cb21-9"><a href=""></a></span>
<span id="cb21-10"><a href=""></a>states      <span class="ot">&lt;-</span> states[<span class="fu">order</span>(states<span class="sc">$</span>state), ]</span>
<span id="cb21-11"><a href=""></a>states_unwt <span class="ot">&lt;-</span> states_unwt[<span class="fu">order</span>(states_unwt<span class="sc">$</span>state), ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Add up the deaths, add up the people, divide once. Same <code>aggregate()</code> template, <code>FUN = sum</code> instead of <code>mean</code>.</p>
<div class="fragment">
<p>Sorting matters: <code>aggregate()</code> returns rows grouped, not alphabetically, and the same <code>set.seed()</code> on a different row order gives a different p-value.</p>
</div>
</section>
<section id="same-39-states-two-different-answers" class="slide level2">
<h2>Same 39 states, two different answers</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href=""></a>gap <span class="ot">&lt;-</span> states_unwt<span class="sc">$</span>crude_rate_20_64 <span class="sc">-</span> states<span class="sc">$</span>crude_rate_20_64</span>
<span id="cb22-2"><a href=""></a><span class="fu">summary</span>(gap)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -6.355  35.360  71.739  63.498  82.872 137.373 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href=""></a>states<span class="sc">$</span>state[<span class="fu">abs</span>(gap) <span class="sc">&gt;</span> <span class="dv">75</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "AR" "AZ" "CA" "FL" "GA" "IL" "KS" "MO" "NC" "ND" "NM" "OK" "OR" "SC"
[15] "SD" "TN" "TX"</code></pre>
</div>
</div>
<div class="fragment">
<p>Texas is off by more than 130 deaths per 100,000, which is larger than any difference we are about to look for. We use the weighted version, because it is the state’s actual rate.</p>
</div>
</section>
<section id="i-read-these" class="slide level2">
<h2>I read these</h2>
<div class="readrow fragment" data-fragment-index="1">
<div class="columns">
<div class="column" style="width:45%;">
<p><code>hist(counties$crude_rate_20_64)</code></p>
</div><div class="column" style="width:55%;">
<p>“Take the <code>crude_rate_20_64</code> column out of <code>counties</code>, and draw a histogram of it.”</p>
</div></div>
</div>
<div class="readrow fragment" data-fragment-index="2">
<div class="columns">
<div class="column" style="width:45%;">
<p><code>d2014 &lt;- counties[counties$year == 2014, ]</code></p>
</div><div class="column" style="width:55%;">
<p>“From <code>counties</code>, keep the rows where <code>year</code> is 2014 and every column, and store that as <code>d2014</code>.”</p>
</div></div>
</div>
<div class="readrow fragment" data-fragment-index="3">
<div class="columns">
<div class="column" style="width:45%;">
<p><code>aggregate(crude_rate_20_64 ~ state, data = d2014, FUN = mean)</code></p>
</div><div class="column" style="width:55%;">
<p>“Using the <code>d2014</code> data, average <code>crude_rate_20_64</code> broken down by <code>state</code>.”</p>
</div></div>
</div>
<div class="readrow fragment" data-fragment-index="4">
<div class="columns">
<div class="column" style="width:45%;">
<p><code>d2014$deaths &lt;- d2014$crude_rate_20_64 * d2014$population_20_64 / 1e5</code></p>
</div><div class="column" style="width:55%;">
<p>“Multiply each county’s rate by its population, divide by 100,000, and store the result as a new column called <code>deaths</code>.”</p>
</div></div>
</div>
</section>
<section id="now-you-read-these" class="slide level2">
<h2>Now you read these</h2>
<div class="readrow">
<div class="columns">
<div class="column" style="width:45%;">
<p><span class="fragment" data-fragment-index="1"><code>table(states$expanded)</code></span></p>
</div><div class="column" style="width:55%;">
<p><span class="fragment" data-fragment-index="2">&nbsp;“Take the <code>expanded</code> column out of <code>states</code>, and count how many of each value there are.”</span></p>
</div></div>
</div>
<div class="readrow">
<div class="columns">
<div class="column" style="width:45%;">
<p><span class="fragment" data-fragment-index="3"><code>high_pov &lt;- states[states$poverty_rate &gt; 20, ]</code></span></p>
</div><div class="column" style="width:55%;">
<p><span class="fragment" data-fragment-index="4">&nbsp;“From <code>states</code>, keep the rows where <code>poverty_rate</code> is above 20 and every column, and store that as <code>high_pov</code>.”</span></p>
</div></div>
</div>
<div class="readrow">
<div class="columns">
<div class="column" style="width:45%;">
<p><span class="fragment" data-fragment-index="5"><code>aggregate(poverty_rate ~ expanded, data = states, FUN = mean)</code></span></p>
</div><div class="column" style="width:55%;">
<p><span class="fragment" data-fragment-index="6">&nbsp;“Using the <code>states</code> data, average <code>poverty_rate</code> broken down by <code>expanded</code>.”</span></p>
</div></div>
</div>
<div class="readrow">
<div class="columns">
<div class="column" style="width:45%;">
<p><span class="fragment" data-fragment-index="7"><code>states$big &lt;- ifelse(states$poverty_rate &gt; 20, 1, 0)</code></span></p>
</div><div class="column" style="width:55%;">
<p><span class="fragment" data-fragment-index="8">&nbsp;“Test whether each state’s <code>poverty_rate</code> is above 20, give it 1 if yes and 0 if no, and store that as a new column called <code>big</code>.”</span></p>
</div></div>
</div>
<aside class="notes">
<p>Reveal the code, take an answer from the room, then reveal the wording. Each one mirrors the example directly above it on the previous slide.</p>
<p>The wording does not have to match mine; the structure does. Listen for whether they start at the right and work back, and whether they say “store it as” for the arrow.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="describe-step-4-look-at-the-comparison" class="slide level2">
<h2>DESCRIBE · Step 4: look at the comparison</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href=""></a><span class="fu">boxplot</span>(crude_rate_20_64 <span class="sc">~</span> expanded, <span class="at">data =</span> states)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="01-rstats-presentation_files/figure-revealjs/unnamed-chunk-14-1.png" class="quarto-figure quarto-figure-center r-stretch" width="864"><div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href=""></a><span class="fu">aggregate</span>(crude_rate_20_64 <span class="sc">~</span> expanded, <span class="at">data =</span> states, <span class="at">FUN =</span> mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  expanded crude_rate_20_64
1        0         390.1661
2        1         350.9884</code></pre>
</div>
</div>
</section>
<section id="describe-step-4-the-estimate-as-one-number" class="slide level2">
<h2>DESCRIBE · Step 4: the estimate, as one number</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href=""></a>group_means <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(crude_rate_20_64 <span class="sc">~</span> expanded,</span>
<span id="cb29-2"><a href=""></a>                         <span class="at">data =</span> states, <span class="at">FUN =</span> mean)</span>
<span id="cb29-3"><a href=""></a>diff_obs <span class="ot">&lt;-</span> group_means<span class="sc">$</span>crude_rate_20_64[<span class="dv">2</span>] <span class="sc">-</span> group_means<span class="sc">$</span>crude_rate_20_64[<span class="dv">1</span>]</span>
<span id="cb29-4"><a href=""></a>diff_obs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -39.17766</code></pre>
</div>
</div>
<p>Expansion states averaged about <strong>64 fewer deaths per 100,000</strong> working-age people.</p>
<p>Is that more than luck would hand us?</p>
</section>
<section id="test-step-5-the-test-you-already-know" class="slide level2">
<h2>TEST · Step 5: the test you already know</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href=""></a><span class="fu">t.test</span>(crude_rate_20_64 <span class="sc">~</span> expanded, <span class="at">data =</span> states)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  crude_rate_20_64 by expanded
t = 1.5435, df = 34.632, p-value = 0.1318
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 -12.37175  90.72706
sample estimates:
mean in group 0 mean in group 1 
       390.1661        350.9884 </code></pre>
</div>
</div>
<p>Read all of it. The <strong>interval</strong> tells you the size of the gap the data supports. The p-value never does.</p>
</section>
<section id="wait-the-sign-flipped" class="slide level2">
<h2>Wait, the sign flipped</h2>
<p>We computed <code>diff_obs = −64</code>. The interval says <strong>+7 to +121</strong>.</p>
<div class="fragment">
<p>That is not an error, and it is not you.</p>
<p><code>t.test()</code> subtracts <strong>group 0 − group 1</strong>. We did <strong>group 1 − group 0</strong>. Same gap, opposite sign. Check it against the group means at the bottom.</p>
</div>
<div class="fragment">
<p>This catches everyone once. When a sign looks wrong, find out which way round the subtraction went before assuming you broke something.</p>
</div>
<div class="fragment">
<p><code>t = 2.29</code> and <code>df = 34.04</code> you can ignore today.</p>
</div>
</section>
<section id="check-step-6-what-does-p-0.13-actually-mean" class="slide level2">
<h2>CHECK · Step 6: what does p = 0.13 actually mean?</h2>
<p>Most of us walk in carrying this one:</p>
<blockquote>
<p><del>“p is the probability the result is due to chance.”</del></p>
</blockquote>
<div class="fragment">
<p>It’s the most common answer, and it has the logic <strong>backwards</strong>. A p-value never tells you the probability that chance caused your result.</p>
</div>
<div class="fragment">
<p>It <strong>assumes chance is all there is</strong>, and then asks:</p>
<blockquote>
<p>if expansion made no difference at all, how often would luck alone hand us a gap as big as ours?</p>
</blockquote>
</div>
</section>
<section id="check-step-6-so-lets-build-one" class="slide level2">
<h2>CHECK · Step 6: so let’s build one</h2>
<ul>
<li class="fragment">The null hypothesis says the labels are meaningless.</li>
<li class="fragment">So let’s <em>make</em> them meaningless by shuffling which states expanded.</li>
<li class="fragment">Do that a thousand times, and we have a thousand worlds where the policy did nothing.</li>
<li class="fragment">Then just count how many of them beat our real result.</li>
</ul>
<div class="fragment">
<p>We don’t have to trust a formula for this. <strong>We can just do it.</strong></p>
</div>
</section>
<section id="step-6-one-fake-world" class="slide level2">
<h2>Step 6: one fake world</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href=""></a>shuffled <span class="ot">&lt;-</span> <span class="fu">sample</span>(states<span class="sc">$</span>expanded)</span>
<span id="cb33-2"><a href=""></a></span>
<span id="cb33-3"><a href=""></a><span class="fu">mean</span>(states<span class="sc">$</span>crude_rate_20_64[shuffled <span class="sc">==</span> <span class="dv">1</span>]) <span class="sc">-</span></span>
<span id="cb33-4"><a href=""></a>  <span class="fu">mean</span>(states<span class="sc">$</span>crude_rate_20_64[shuffled <span class="sc">==</span> <span class="dv">0</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 23.38928</code></pre>
</div>
</div>
<p>Run it again:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a>shuffled <span class="ot">&lt;-</span> <span class="fu">sample</span>(states<span class="sc">$</span>expanded)</span>
<span id="cb35-2"><a href=""></a><span class="fu">mean</span>(states<span class="sc">$</span>crude_rate_20_64[shuffled <span class="sc">==</span> <span class="dv">1</span>]) <span class="sc">-</span></span>
<span id="cb35-3"><a href=""></a>  <span class="fu">mean</span>(states<span class="sc">$</span>crude_rate_20_64[shuffled <span class="sc">==</span> <span class="dv">0</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -52.08244</code></pre>
</div>
</div>
<p>That bouncing <strong>is</strong> sampling variation. You are looking straight at it.</p>
</section>
<section id="step-6-a-thousand-fake-worlds" class="slide level2">
<h2>Step 6: a thousand fake worlds</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb37-2"><a href=""></a>diffs <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>, {</span>
<span id="cb37-3"><a href=""></a>  shuffled <span class="ot">&lt;-</span> <span class="fu">sample</span>(states<span class="sc">$</span>expanded)</span>
<span id="cb37-4"><a href=""></a>  <span class="fu">mean</span>(states<span class="sc">$</span>crude_rate_20_64[shuffled <span class="sc">==</span> <span class="dv">1</span>]) <span class="sc">-</span></span>
<span id="cb37-5"><a href=""></a>    <span class="fu">mean</span>(states<span class="sc">$</span>crude_rate_20_64[shuffled <span class="sc">==</span> <span class="dv">0</span>])</span>
<span id="cb37-6"><a href=""></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>replicate()</code> does a thing <code>n</code> times and keeps the answers.</p>
<p>One thousand worlds in which the policy did nothing.</p>
</section>
<section id="step-6-and-there-it-is" class="slide level2">
<h2>Step 6: and there it is</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href=""></a><span class="fu">hist</span>(diffs)</span>
<span id="cb38-2"><a href=""></a><span class="fu">abline</span>(<span class="at">v =</span> diff_obs, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

</div>
<img data-src="01-rstats-presentation_files/figure-revealjs/unnamed-chunk-21-1.png" class="quarto-figure quarto-figure-center r-stretch" width="864"><div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href=""></a><span class="fu">mean</span>(<span class="fu">abs</span>(diffs) <span class="sc">&gt;=</span> <span class="fu">abs</span>(diff_obs))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.139</code></pre>
</div>
</div>
<p>Same <code>hist()</code> from step 2, pointed at something new. That number is a p-value you built out of <code>sample()</code>, <code>mean()</code>, and counting.</p>
</section>
<section id="that-one-line-does-three-things" class="slide level2">
<h2>That one line does three things</h2>
<div class="sourceCode" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href=""></a><span class="fu">mean</span>( <span class="fu">abs</span>(diffs) <span class="sc">&gt;=</span> <span class="fu">abs</span>(diff_obs) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<tbody>
<tr class="odd">
<td><code>abs()</code></td>
<td>drops the minus sign, so we count both tails: past −39 and past +39. That is what “two-sided” means, and it is what <code>t.test()</code> did.</td>
</tr>
<tr class="even">
<td><code>&gt;=</code></td>
<td>gives a <code>TRUE</code>/<code>FALSE</code> for each of the 1000 shuffles</td>
</tr>
<tr class="odd">
<td><code>mean()</code></td>
<td>of <code>TRUE</code>/<code>FALSE</code> gives the proportion that are <code>TRUE</code>, because <code>TRUE</code> counts as 1</td>
</tr>
</tbody>
</table>
</section>
<section id="drop-the-abs-and-see" class="slide level2">
<h2>Drop the <code>abs()</code> and see</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href=""></a><span class="fu">mean</span>(diffs <span class="sc">&gt;=</span> diff_obs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.93</code></pre>
</div>
</div>
<div class="fragment">
<p>0.93, not something near 0.07. Our difference is negative, so “shuffles at least as large as ours” counts almost all of them.</p>
</div>
<div class="fragment">
<p>R does not warn you. If you want the one-sided p in the direction of the effect, it is <code>mean(diffs &lt;= diff_obs)</code>. Getting this wrong returns a number, not an error.</p>
</div>
</section>
<section id="why-it-doesnt-exactly-match-t.test" class="slide level2">
<h2>Why it doesn’t exactly match <code>t.test()</code></h2>
<p>Permutation gave <code>0.139</code>. The t-test gave <code>0.132</code>.</p>
<ul>
<li class="fragment"><code>t.test()</code> assumes the difference follows a normal distribution. The shuffle does not. It does assume the labels could have been dealt out any other way, which is true here because each state chose once.</li>
<li class="fragment">1000 shuffles is itself a sample. Change the seed and the second digit moves. Run 10,000 if that matters to you.</li>
</ul>
<div class="fragment">
<p>Two methods, same conclusion: this difference is not distinguishable from chance with 39 states.</p>
</div>
</section>
<section id="model-step-7-the-same-answer-as-a-regression" class="slide level2">
<h2>MODEL · Step 7: the same answer, as a regression</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href=""></a>m <span class="ot">&lt;-</span> <span class="fu">lm</span>(crude_rate_20_64 <span class="sc">~</span> expanded, <span class="at">data =</span> states)</span>
<span id="cb44-2"><a href=""></a><span class="fu">summary</span>(m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = crude_rate_20_64 ~ expanded, data = states)

Residuals:
    Min      1Q  Median      3Q     Max 
-126.81  -55.30  -20.92   52.62  192.52 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   390.17      19.08  20.454   &lt;2e-16 ***
expanded      -39.18      25.40  -1.543    0.131    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 78.65 on 37 degrees of freedom
Multiple R-squared:  0.06043,   Adjusted R-squared:  0.03503 
F-statistic:  2.38 on 1 and 37 DF,  p-value: 0.1314</code></pre>
</div>
</div>
</section>
<section id="model-step-7-you-need-two-numbers-from-that" class="slide level2">
<h2>MODEL · Step 7: you need two numbers from that</h2>
<p>Both on the <strong><code>expanded</code></strong> row:</p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>Estimate</code></td>
<td><strong>−39.18</strong></td>
<td>our difference in means, exactly</td>
</tr>
<tr class="even">
<td><code>Pr(&gt;|t|)</code></td>
<td><strong>0.13</strong></td>
<td>our p-value</td>
</tr>
</tbody>
</table>
<p>And one bonus, on the row above: <code>(Intercept)</code> is the mean of the group coded 0 — the same number from step 4. The intercept is just the baseline group.</p>
<div class="fragment">
<p>Everything else (Residuals, Std. Error, R-squared, F-statistic) answers questions we haven’t asked. You are <strong>not</strong> missing something by skipping them today.</p>
</div>
</section>
<section id="model-step-7-look-what-happened" class="slide level2">
<h2>MODEL · Step 7: look what happened</h2>
<p>A difference in means <em>is</em> a regression coefficient.</p>
<p>t-test, permutation test, and regression are three ways of asking one question, and they agree.</p>
<div class="fragment">
<p>Once you can read this output you can read most quantitative papers.</p>
</div>
<div class="fragment">
<p>(<code>t.test()</code> uses Welch’s correction by default, which is also why its <code>df</code> was 34.04 rather than 37. <code>var.equal = TRUE</code> matches <code>lm()</code> to the decimal.)</p>
</div>
</section>
<section id="step-8-why-we-used-39-rows-and-not-2372" class="slide level2">
<h2>Step 8: why we used 39 rows and not 2,372</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href=""></a><span class="fu">t.test</span>(crude_rate_20_64 <span class="sc">~</span> expanded, <span class="at">data =</span> d2014)<span class="sc">$</span>p.value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.687914e-17</code></pre>
</div>
</div>
<p>That is the same test, run on the counties.</p>
<div class="fragment">
<p><code>p</code> is about 6e-17. Overwhelming, and wrong.</p>
</div>
<div class="fragment">
<p>It believes it has 2,372 independent observations. It has 39. Every county in a state shares one policy decision, so those rows repeat 39 pieces of information rather than adding 2,372 new ones.</p>
</div>
<div class="fragment">
<p>When a p-value looks too good, ask how many independent things you actually measured. It is usually fewer than the number of rows.</p>
</div>
</section>
<section id="that-was-the-whole-game" class="slide level2">
<h2>That was the whole game</h2>
<pre><code>read.csv  dim  names  head  summary     hist  boxplot  abline
ifelse  is.na  table                    aggregate  mean  median  abs  range
c  order                                t.test  lm
sample  set.seed  replicate</code></pre>
<p>Twenty-three functions, and you have a difference in means, a permutation test, and a regression, plus the reason to distrust one of them.</p>
</section>
<section id="glossary-the-twenty-three-functions" class="slide level2">
<h2>Glossary: the twenty-three functions</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div style="font-size: 0.58em;">
<p><strong>Get data, look at it</strong></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>read.csv()</code></td>
<td>read a spreadsheet off disk</td>
</tr>
<tr class="even">
<td><code>dim()</code></td>
<td>how many rows and columns</td>
</tr>
<tr class="odd">
<td><code>names()</code></td>
<td>what are the columns called</td>
</tr>
<tr class="even">
<td><code>head()</code></td>
<td>show the first few rows</td>
</tr>
<tr class="odd">
<td><code>summary()</code></td>
<td>six-number sketch of a column</td>
</tr>
</tbody>
</table>
<p><strong>Pictures</strong></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>hist()</code></td>
<td>distribution of one variable</td>
</tr>
<tr class="even">
<td><code>boxplot()</code></td>
<td>compare groups</td>
</tr>
<tr class="odd">
<td><code>abline()</code></td>
<td>add a line to the last plot</td>
</tr>
</tbody>
</table>
<p><strong>Build a grouping variable</strong></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>ifelse()</code></td>
<td>test each value, return 1 or 0</td>
</tr>
<tr class="even">
<td><code>is.na()</code></td>
<td>is this value missing?</td>
</tr>
<tr class="odd">
<td><code>table()</code></td>
<td>count how many in each category</td>
</tr>
</tbody>
</table>
</div>
</div><div class="column" style="width:50%;">
<div style="font-size: 0.58em;">
<p><strong>Summarise</strong></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>aggregate()</code></td>
<td>apply a function, split by group</td>
</tr>
<tr class="even">
<td><code>mean()</code></td>
<td>average, and on TRUE/FALSE a proportion</td>
</tr>
<tr class="odd">
<td><code>median()</code></td>
<td>the middle value</td>
</tr>
<tr class="even">
<td><code>abs()</code></td>
<td>drop the minus sign</td>
</tr>
<tr class="odd">
<td><code>range()</code></td>
<td>smallest and largest</td>
</tr>
<tr class="even">
<td><code>c()</code></td>
<td>glue values into one vector</td>
</tr>
<tr class="odd">
<td><code>order()</code></td>
<td>the positions that would sort something</td>
</tr>
</tbody>
</table>
<p><strong>Test and model</strong></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>t.test()</code></td>
<td>compare two group means</td>
</tr>
<tr class="even">
<td><code>lm()</code></td>
<td>fit a linear model</td>
</tr>
<tr class="odd">
<td><code>summary()</code></td>
<td>also prints a model’s coefficient table</td>
</tr>
</tbody>
</table>
<p><strong>The permutation test</strong></p>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>sample()</code></td>
<td>shuffle into a random order</td>
</tr>
<tr class="even">
<td><code>set.seed()</code></td>
<td>make the shuffling repeatable</td>
</tr>
<tr class="odd">
<td><code>replicate()</code></td>
<td>do something n times, keep the answers</td>
</tr>
</tbody>
</table>
</div>
<div style="font-size: 0.72em; margin-top: 0.5em;">
<p>Two more appear only in the finish-early extensions: <code>plot()</code> and <code>sum()</code>.</p>
</div>
</div></div>
</section>
<section id="glossary-the-symbols" class="slide level2">
<h2>Glossary: the symbols</h2>
<div style="font-size: 0.66em;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="odd">
<td><code>#</code></td>
<td>everything after it is ignored</td>
<td><code># this is a note</code></td>
</tr>
<tr class="even">
<td><code>&lt;-</code></td>
<td>store this as</td>
<td><code>x &lt;- 5</code></td>
</tr>
<tr class="odd">
<td><code>=</code></td>
<td>name an argument, <em>inside</em> a function</td>
<td><code>data = states</code></td>
</tr>
<tr class="even">
<td><code>()</code></td>
<td>run a function; what it needs goes inside</td>
<td><code>mean(x)</code></td>
</tr>
<tr class="odd">
<td><code>,</code></td>
<td>separates one argument from the next</td>
<td><code>hist(x, breaks = 20)</code></td>
</tr>
<tr class="even">
<td><code>$</code></td>
<td>pull one column out of a data frame</td>
<td><code>states$expanded</code></td>
</tr>
<tr class="odd">
<td><code>~</code></td>
<td>“broken down by”</td>
<td><code>rate ~ expanded</code></td>
</tr>
<tr class="even">
<td><code>==</code></td>
<td><em>is</em> equal to: a question, not an instruction</td>
<td><code>year == 2014</code></td>
</tr>
<tr class="odd">
<td><code>&gt;=</code> <code>&lt;=</code> <code>&gt;</code> <code>&lt;</code></td>
<td>the usual comparisons</td>
<td><code>diffs &gt;= 64</code></td>
</tr>
<tr class="even">
<td><code>!</code></td>
<td>not</td>
<td><code>!is.na(x)</code></td>
</tr>
<tr class="odd">
<td><code>&amp;</code></td>
<td>and</td>
<td><code>!is.na(x) &amp; x == 2014</code></td>
</tr>
<tr class="even">
<td><code>{ }</code></td>
<td>treat several lines as one block</td>
<td>inside <code>replicate()</code></td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p><code>=</code> and <code>&lt;-</code> both assign, and you will see both. We use <code>&lt;-</code> for storing things and keep <code>=</code> for naming arguments. It makes the two jobs visible.</p>
</div>
</section>
<section id="glossary-square-brackets-do-three-jobs" class="slide level2">
<h2>Glossary: square brackets do three jobs</h2>
<p>The one that catches everyone. Same symbol, three different meanings:</p>
<div style="font-size: 0.78em;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="odd">
<td><code>df[rows, cols]</code></td>
<td>slice a <strong>table</strong>, note the comma</td>
<td><code>counties[counties$year == 2014, ]</code></td>
</tr>
<tr class="even">
<td><code>x[2]</code></td>
<td>pick one element out of a <strong>vector</strong></td>
<td><code>group_means$crude_rate_20_64[2]</code></td>
</tr>
<tr class="odd">
<td><code>x[test]</code></td>
<td>keep the elements where a test is TRUE</td>
<td><code>states$crude_rate_20_64[shuffled == 1]</code></td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p>If you get <code>undefined columns selected</code>, you almost certainly left out the comma in the first form.</p>
</div>
</section></section>
<section>
<section id="module-2-we-do" class="title-slide slide level1 center">
<h1>Module 2: We do</h1>

</section>
<section id="your-turn-with-a-partner" class="slide level2">
<h2>Your turn, with a partner</h2>
<p>Open <code>scripts/02-we-do.R</code>.</p>
<blockquote>
<p><strong>Do high-poverty states have higher working-age mortality?</strong></p>
</blockquote>
<ul>
<li class="fragment">Same eight steps. Same template. New grouping variable.</li>
<li class="fragment">Where you see <code>______</code>, fill it in.</li>
<li class="fragment"><strong>One types, one reads the code out loud and predicts</strong> what it will do before you run it. Swap at step 4.</li>
<li class="fragment">Stuck two minutes? Red sticky. Don’t burn the module on one blank.</li>
</ul>
</section>
<section id="whats-new-in-module-2" class="slide level2">
<h2>What’s new in Module 2</h2>
<p>Two things you have not seen:</p>
<p><strong>Making groups from a number.</strong> Expansion came ready-made as 0/1. Poverty is continuous, so you split it at the median with <code>ifelse()</code>.</p>
<p><strong>A result that runs off the page.</strong> Your observed difference may fall outside the whole null distribution:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href=""></a><span class="fu">hist</span>(diffs, <span class="at">xlim =</span> <span class="fu">range</span>(<span class="fu">c</span>(diffs, diff_obs)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="fragment">
<p>If <code>mean(abs(diffs) &gt;= abs(diff_obs))</code> gives you <code>0</code>, that is not p = 0. None of 1000 shuffles got that far, so <strong>report p &lt; 0.001</strong>.</p>
</div>
</section></section>
<section>
<section id="module-3-you-do" class="title-slide slide level1 center">
<h1>Module 3: You do</h1>

</section>
<section id="on-your-own" class="slide level2">
<h2>On your own</h2>
<p>Open <code>scripts/03-they-do.R</code>.</p>
<blockquote>
<p><strong>Do states with above-median unemployment have higher working-age mortality?</strong></p>
</blockquote>
<ul>
<li class="fragment">Eight steps, no code. You have done all eight, twice.</li>
<li class="fragment">Modules 1 and 2 are open in your other tabs. <strong>Use them</strong>.</li>
<li class="fragment">Copying your own working code and changing a variable name is not cheating. It is the job.</li>
<li class="fragment">Step 8 asks you to write the finding in prose. Do that one.</li>
</ul>
</section>
<section id="if-you-finish-early" class="slide level2 scrollable">
<h2>If you finish early</h2>
<ol type="1">
<li class="fragment">Swap the grouping to <code>median_income</code>. Does the story change?</li>
<li class="fragment">You split at the median, which threw information away. Try it continuous: <code>plot()</code>, then <code>abline(lm(...))</code>. What did the split cost?</li>
<li class="fragment">Put two predictors in one model. Watch what happens to each.</li>
<li class="fragment"><strong>Point today’s script at your own data.</strong> That is the actual goal, and we are here for another twenty minutes.</li>
</ol>
</section></section>
<section>
<section id="where-this-goes" class="title-slide slide level1 center">
<h1>Where this goes</h1>

</section>
<section id="what-today-deliberately-left-out" class="slide level2">
<h2>What today deliberately left out</h2>
<ul>
<li class="fragment"><strong><code>ggplot2</code></strong> for nicer plots. Workshop 09.</li>
<li class="fragment"><strong><code>dplyr</code> / the tidyverse</strong> for nicer data wrangling. Workshop 03.</li>
<li class="fragment"><strong>Regression properly</strong>: more than one predictor, and what the assumptions buy you.</li>
<li class="fragment"><strong>Quarto</strong>, turning a script into a paper. Two minutes, right now.</li>
</ul>
<div class="fragment">
<p>None of it is a prerequisite for what you did today. You can start Monday with twenty-three functions.</p>
</div>
</section>
<section id="two-rules-for-your-own-work" class="slide level2">
<h2>Two rules for your own work</h2>
<p><strong>Always open the folder.</strong> Never write <code>setwd("/Users/you/...")</code>. It works on exactly one computer, and not for long. Open the project folder and every path in your script stays relative.</p>
<p><strong>Never use <code>rm(list = ls())</code>.</strong> It does not give you a clean session; it doesn’t unload packages or reset options. Restart R instead: <strong>Cmd/Ctrl+Shift+0</strong>.</p>
<div class="fragment">
<p>If a script only runs after you have run some <em>other</em> thing first, it isn’t finished.</p>
</div>
</section>
<section id="where-to-get-unstuck" class="slide level2">
<h2>Where to get unstuck</h2>
<table class="caption-top">
<tbody>
<tr class="odd">
<td><code>?mean</code></td>
<td>R’s own help, and it is better than it looks</td>
</tr>
<tr class="even">
<td><strong>StatLab office hours</strong></td>
<td>a human, free, and the fastest option</td>
</tr>
<tr class="odd">
<td>Error message → search</td>
<td>paste it verbatim, someone has had it</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Your script from today is the best reference you now own. It works, you typed it, and you know what every line does.</p>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="01-rstats-presentation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="01-rstats-presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="01-rstats-presentation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="01-rstats-presentation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="01-rstats-presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="01-rstats-presentation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="01-rstats-presentation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="01-rstats-presentation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="01-rstats-presentation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="01-rstats-presentation_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>